version: "3"
services:
  sbt:
    image: 'grupoabraxas/sbt-docker'
    user: ${UID}:${GID}
    working_dir: ${PWD}
    volumes:
      - ../:${PWD}
      - ../:/root
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ETC_PASSWD-/etc/passwd}:/etc/passwd:ro
      - ${ETC_GROUP-/etc/group}:/etc/group:ro
      - ${HOME}:${HOME}
    network_mode: host
    entrypoint:
      - sbt
