version: "3"
services:
  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 32181"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 32181:32181
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
  kafka:
    image: confluentinc/cp-kafka:5.4.0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 29092"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      # For exactly_once
      # transaction.state.log.replication.factor
      # transaction.state.log.min.isr
